### ISSUE TITLE
hey do you mind if i make a few alterations to the script and share it?

### ISSUE THREAD

**Issue by warlord500** [Utkarshkj/HabiticaIntegrations#1]
i wanted to make a few alterations to the script and share them obviously giving credit to you. 
my changes were things like include the start and end time in an event and the date in the title! 
possibly making work events worth hard instead of medium! 

you should add a license say [MIT](https://opensource.org/licenses/MIT) and put your name at the top!

**Comment by Utkarshkj** [comment]
Go ahead !!
I would love people to build on my work :)
